{
  "formatVersion": "1.1",
  "component": {
    "group": "org.sigmechanics.spark",
    "module": "common",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-1.5.0.jar",
          "url": "common-1.5.0.jar",
          "size": 17150,
          "sha512": "d900ed00c4be14c37c8472a9eab5adb1363803d435214f349722abad9347c3311e9273bf22943c699b68db273f04fd62438befdc8fd330904cd1ea491e1afc08",
          "sha256": "afd5d64f4faefc7b7b14041b7e637fa8f6f5eb345a60760c5d7c8dfd9f27ab00",
          "sha1": "2e95237b6d6207a513329e1a14feda7ea4012b67",
          "md5": "96aaacd5405717c553c2f7bceda8839d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.sigmechanics.spark",
          "module": "tools",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "7.0.0.202409031743-r"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.5.0.jar",
          "url": "common-1.5.0.jar",
          "size": 17150,
          "sha512": "d900ed00c4be14c37c8472a9eab5adb1363803d435214f349722abad9347c3311e9273bf22943c699b68db273f04fd62438befdc8fd330904cd1ea491e1afc08",
          "sha256": "afd5d64f4faefc7b7b14041b7e637fa8f6f5eb345a60760c5d7c8dfd9f27ab00",
          "sha1": "2e95237b6d6207a513329e1a14feda7ea4012b67",
          "md5": "96aaacd5405717c553c2f7bceda8839d"
        }
      ]
    }
  ]
}
